on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            # mark down??
            ## hoge
            - aaa
            - bbb
            - [google](google.com)
            - $GITHUB_TOKEN
            - ${{ secrets.GITHUB_TOKEN }}
            - ${{ secrets.GITHUB_TOKEN }}-aiueo!!
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
