name: notify-example

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "AWS認証情報を設定"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: "SSMのパラメータストアからファイルを生成する"
        run: |
          aws ssm get-parameter --name '/sample/text' --with-decryption --query 'Parameter.Value' --output text > sample.txt
        working-directory: .

